import type { SchemaTable, ForeignKey } from "../../types";
import { pgTypeToTs } from "../shared/pgTypeMap";
import { toPascalCase, toCamelCase, singularize } from "../shared/naming";

export interface TsGeneratorOptions {
  interfaceNameStrategy: (tableName: string) => string;
  fieldNameStrategy: (columnName: string) => string;
  optionalForNullable: boolean;
  exportKeyword: boolean;
}

export interface TsGenerateResult {
  code: string;
  warnings: string[];
}

const DEFAULT_OPTIONS: TsGeneratorOptions = {
  interfaceNameStrategy: (tableName) => toPascalCase(singularize(tableName)),
  fieldNameStrategy: (columnName) => toCamelCase(columnName),
  optionalForNullable: true,
  exportKeyword: true,
};

/**
 * Generates TS interfaces for API/wire-facing consumers from a schema. Like
 * the Go generator, no FK relation fields are synthesized in this phase —
 * each FK column is just its own scalar field (documented limitation).
 */
export function buildTsInterfaces(
  tables: SchemaTable[],
  _foreignKeys: ForeignKey[],
  options?: Partial<TsGeneratorOptions>,
): TsGenerateResult {
  const opts: TsGeneratorOptions = { ...DEFAULT_OPTIONS, ...options };
  const warnings: string[] = [];
  const blocks: string[] = [];

  for (const table of tables) {
    const interfaceName = opts.interfaceNameStrategy(table.name);
    const lines: string[] = [];

    for (const col of table.columns) {
      const { tsType, isUnsupported } = pgTypeToTs(col.type);
      if (isUnsupported) {
        warnings.push(`Unsupported type "${col.type}" on "${table.name}.${col.name}" — mapped to ${tsType}`);
      }

      const fieldName = opts.fieldNameStrategy(col.name);
      const nullable = col.isNullable && !col.isPrimaryKey;
      const optionalMark = nullable && opts.optionalForNullable ? "?" : "";
      const typeStr = nullable ? `${tsType} | null` : tsType;

      lines.push(`  ${fieldName}${optionalMark}: ${typeStr};`);
    }

    const exportStr = opts.exportKeyword ? "export " : "";
    blocks.push(`${exportStr}interface ${interfaceName} {\n${lines.join("\n")}\n}`);
  }

  const header = "// Generated by SchemaViz — https://app.schemaviz.mystaline.dev";
  const code = [header, ...blocks.map((b) => "\n" + b)].join("\n");

  return { code, warnings };
}
