import type { SchemaTable, ForeignKey } from "../../types";
import { pgTypeToGo } from "../shared/pgTypeMap";
import { toPascalCase, singularize, pluralize } from "../shared/naming";

export type TagValueNaming = "bare" | "tablePrefixed" | ((table: string, column: string) => string);

export interface GoGeneratorOptions {
  packageName: string;
  tags: { json: boolean; db: boolean };
  tagValueNaming: TagValueNaming;
  pointerForNullable: boolean;
  structNameStrategy: (tableName: string) => string;
  fieldNameStrategy: (columnName: string) => string;
}

export interface GoGenerateResult {
  code: string;
  warnings: string[];
}

const DEFAULT_OPTIONS: GoGeneratorOptions = {
  packageName: "models",
  tags: { json: true, db: true },
  tagValueNaming: "bare",
  pointerForNullable: true,
  structNameStrategy: (tableName) => toPascalCase(singularize(tableName)),
  fieldNameStrategy: (columnName) => toPascalCase(columnName),
};

function computeTagValue(table: string, column: string, naming: TagValueNaming): string {
  if (typeof naming === "function") return naming(table, column);
  if (naming === "tablePrefixed") return `${pluralize(table).toLowerCase()}_${column.toLowerCase()}`;
  return column.toLowerCase();
}

/**
 * Generates plain Go structs (no ORM dependency) from a schema. FK columns
 * are emitted as ordinary scalar fields — no relation/association fields are
 * synthesized in this phase (documented limitation, keeps output simple and
 * matches the same choice made for the TS generator).
 */
export function buildGoStructs(
  tables: SchemaTable[],
  _foreignKeys: ForeignKey[],
  options?: Partial<GoGeneratorOptions>,
): GoGenerateResult {
  const opts: GoGeneratorOptions = {
    ...DEFAULT_OPTIONS,
    ...options,
    tags: { ...DEFAULT_OPTIONS.tags, ...options?.tags },
  };

  const warnings: string[] = [];
  const usedImports = new Set<string>();
  const structBlocks: string[] = [];

  for (const table of tables) {
    const structName = opts.structNameStrategy(table.name);
    const lines: string[] = [];

    for (const col of table.columns) {
      const { goType, imports, isUnsupported } = pgTypeToGo(col.type);
      imports.forEach((imp) => usedImports.add(imp));
      if (isUnsupported) {
        warnings.push(`Unsupported type "${col.type}" on "${table.name}.${col.name}" — mapped to ${goType}`);
      }

      const fieldName = opts.fieldNameStrategy(col.name);
      const nullable = col.isNullable && !col.isPrimaryKey;
      const fieldType = nullable && opts.pointerForNullable ? `*${goType}` : goType;

      const tagValue = computeTagValue(table.name, col.name, opts.tagValueNaming);
      const tagParts: string[] = [];
      if (opts.tags.json) tagParts.push(`json:"${tagValue}"`);
      if (opts.tags.db) tagParts.push(`db:"${tagValue}"`);
      const tagStr = tagParts.length > 0 ? ` \`${tagParts.join(" ")}\`` : "";

      lines.push(`\t${fieldName} ${fieldType}${tagStr}`);
    }

    structBlocks.push(`type ${structName} struct {\n${lines.join("\n")}\n}`);
  }

  const importLines: string[] = [];
  if (usedImports.size > 0) {
    const sorted = [...usedImports].sort();
    if (sorted.length === 1) {
      importLines.push(`import "${sorted[0]}"`);
    } else {
      importLines.push("import (", ...sorted.map((imp) => `\t"${imp}"`), ")");
    }
  }

  const headerLines = [
    "// Generated by SchemaViz — https://app.schemaviz.mystaline.dev",
    "",
    `package ${opts.packageName}`,
  ];
  if (importLines.length > 0) headerLines.push("", ...importLines);

  const code = [headerLines.join("\n"), ...structBlocks.map((b) => "\n" + b)].join("\n");

  return { code, warnings };
}
